name: CI Local Repo Registry

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Get current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Check Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."repo.internal:5000"]
              http = true
              insecure = true

      - name: Build and push to local registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            repo.internal:5000/looper:${{ steps.date.outputs.date }} 
            repo.internal:5000/looper:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect repo.internal:5000/looper:latest